'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path');
const { repo, initRepo } = require('./helpers'); const { loadState, saveState } = require('../lib/state'); const { preToolUse, shellModifies } = require('../lib/hooks/preToolUse'); const { resolve } = require('../lib/commands/resolve'); const { stopHook } = require('../lib/hooks/stopHook');
const { userPromptSubmit } = require('../lib/hooks/userPromptSubmit');
function pending(root) { initRepo(root); const s = loadState(root); s.quizPending = true; s.pendingQuizDiff = { totalChangedLines: 2, filesChanged: ['base.txt'], fileCount: 1, insertions: 2, deletions: 0, diff: '+x' }; saveState(root, s); }
test('gates canonical and Claude edit aliases while allowing read-only shell', t => { const r = repo(); t.after(r.cleanup); pending(r.root); for (const tool_name of ['apply_patch', 'Edit', 'Write', 'MultiEdit', 'NotebookEdit']) assert.equal(preToolUse(r.root, { tool_name }).hookSpecificOutput.permissionDecision, 'deny'); assert.equal(shellModifies('sed -i "s/a/b/" src/example.js'), true); assert.equal(preToolUse(r.root, { tool_name: 'Bash', tool_input: { command: 'sed -i "s/a/b/" src/example.js' } }).hookSpecificOutput.permissionDecision, 'deny'); assert.equal(preToolUse(r.root, { tool_name: 'Bash', tool_input: { command: 'git status --short' } }), null); });
test('pending check-in context uses the documented UserPromptSubmit output shape', t => { const r = repo(); t.after(r.cleanup); pending(r.root); const out = userPromptSubmit(r.root); assert.equal(out.hookSpecificOutput.hookEventName, 'UserPromptSubmit'); assert.match(out.hookSpecificOutput.additionalContext, /one at a time.*wait for the real user reply/i); });
test('snapshot includes untracked files without changing index, branch, or HEAD', t => { const r = repo(); t.after(r.cleanup); initRepo(r.root); const beforeIndex = fs.readFileSync(path.join(r.root, '.git/index')); const head = r.run(['rev-parse', 'HEAD']); const branch = r.run(['branch', '--show-current']); fs.writeFileSync(path.join(r.root, 'new.txt'), 'hello\n'); const s = loadState(r.root); const d = require('../lib/gitDiff').captureDiff(r.root, s); assert.ok(d.filesChanged.includes('new.txt')); assert.equal(r.run(['rev-parse', 'HEAD']), head); assert.equal(r.run(['branch', '--show-current']), branch); assert.deepEqual(fs.readFileSync(path.join(r.root, '.git/index')), beforeIndex); });
test('resolve advances checkpoint, records history, and clears pending state', t => { const r = repo(); t.after(r.cleanup); pending(r.root); fs.writeFileSync(path.join(r.root, 'new.txt'), 'change\n'); const prior = loadState(r.root).checkpointRef; resolve(r.root, { result: 'pass', summary: 'Explained behavior' }); const s = loadState(r.root); assert.equal(s.quizPending, false); assert.notEqual(s.checkpointRef, prior); assert.match(fs.readFileSync(path.join(r.root, '.professorx/checkins.jsonl'), 'utf8'), /Explained behavior/); });
test('failed check-ins remember topics and topics due list is sorted', t => { const r = repo(); t.after(r.cleanup); pending(r.root); assert.throws(() => resolve(r.root, { result: 'fail' }), /--topic is required/); resolve(r.root, { result: 'fail', topic: 'Async errors', summary: 'Explained retry behavior' }); let s = loadState(r.root); assert.equal(s.topics[0].misses, 1); assert.equal(s.topics[0].topic, 'Async errors'); pending(r.root); resolve(r.root, { result: 'fail', topic: 'async ERRORS', summary: 'Second review' }); s = loadState(r.root); assert.equal(s.topics.length, 1); assert.equal(s.topics[0].misses, 2); const { topics } = require('../lib/commands/topics'); assert.match(topics(r.root, true), /Async errors — 2 misses/); });
test('12 denied changes automatically close a stalled check-in', t => { const r = repo(); t.after(r.cleanup); pending(r.root); const s = loadState(r.root); s.denyCount = 11; saveState(r.root, s); const out = preToolUse(r.root, { tool_name: 'Edit' }); assert.match(out.systemMessage, /automatically closed/); assert.equal(loadState(r.root).quizPending, false); });
test('diff safety and allow rules include dry-run clean', () => { assert.equal(shellModifies('git clean -n'), false); assert.equal(shellModifies('git clean --dry-run'), false); assert.equal(shellModifies('git clean -fd'), true); assert.equal(shellModifies('git clean -fd && echo -n done'), true); assert.equal(shellModifies('echo hi 2>&1'), false); assert.equal(shellModifies('echo hi 1>output.txt'), true); });
test('Stop hook detects either threshold and never returns a blocking decision', t => { const r = repo(); t.after(r.cleanup); initRepo(r.root); const s = loadState(r.root); s.config.lineThreshold = 1000; s.config.fileThreshold = 1; saveState(r.root, s); fs.writeFileSync(path.join(r.root, 'changed.txt'), 'added\n'); assert.equal(stopHook(r.root), null); assert.equal(loadState(r.root).quizPending, true); const r2 = repo(); t.after(r2.cleanup); initRepo(r2.root); const s2 = loadState(r2.root); s2.config.lineThreshold = 1; s2.config.fileThreshold = 100; saveState(r2.root, s2); fs.writeFileSync(path.join(r2.root, 'base.txt'), 'many changed lines\n'.repeat(5)); assert.equal(stopHook(r2.root), null); assert.equal(loadState(r2.root).quizPending, true); });
test('hook installation is idempotent, preserves unrelated handlers, and uninstall is selective', t => { const r = repo(); t.after(r.cleanup); const f = path.join(r.root, '.claude/settings.local.json'); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, JSON.stringify({ setting: true, hooks: { Stop: [{ hooks: [{ type: 'command', command: 'node custom.js' }] }] } })); initRepo(r.root); const first = fs.readFileSync(f, 'utf8'); initRepo(r.root); const second = fs.readFileSync(f, 'utf8'); assert.equal(first, second); const { uninstall } = require('../lib/commands/uninstall'); uninstall(r.root); const config = JSON.parse(fs.readFileSync(f)); assert.equal(config.setting, true); assert.equal(config.hooks.Stop[0].hooks[0].command, 'node custom.js'); });
test('generated package files contain no machine-specific absolute paths or credential markers', () => { const root = path.resolve(__dirname, '..'); const files = require('node:child_process').execFileSync('find', [root, '-type', 'f', '-not', '-path', '*/.git/*'], { encoding: 'utf8' }).trim().split('\n'); const forbidden = new RegExp(`${String.fromCharCode(47)}(?:Users|home)${String.fromCharCode(47)}[A-Za-z0-9._-]+`); for (const file of files) { const text = fs.readFileSync(file, 'utf8'); assert.equal(forbidden.test(text), false, `machine-specific path in ${path.basename(file)}`); assert.doesNotMatch(text, /(?:api[_-]?key|password|credential|secret)\s*[:=]\s*['"][^'"]+/i); } });
